#!/bin/sh
if [[ $EUID -ne 0 ]]; then
   echo "This must be run as root" 1>&2
   exit 1
fi

case $1 in
	lock)   mode=+i ;;
	unlock) mode=-i ;;
	*)
		echo 'Usage : cfg <lock|unlock>.'
		exit 0
	;;
esac

chattr $mode ~/.zshrc
chattr $mode ~/.zshenv
chattr $mode ~/.vimrc
chattr -R $mode ~/.git
